services:
  minilib_app:
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - service_npm_token
      args:
        HENDEC_NPM_REGISTERY_HOST: ${HENDEC_NPM_REGISTERY_HOST}
        HENDEC_NPM_REGISTERY_PORT: ${HENDEC_NPM_REGISTERY_PORT}

    ##### END BUILD CONF - START compose up arg ##########################
    environment:
      PORT: 5001
      NODE_ENV: development
      DB_HOST: 192.168.100.10
      DB_PORT: 5432
      DB_NAME: minilib
      DB_USER: minilib_user
      DB_PASSWORD_FILE: /run/secrets/db_minilib_password
    ports:
      - "5001:5001"
    secrets:
      - db_minilib_password

secrets:
  db_minilib_password:
    name: db_minilib_password
    file: /home/afpa/.secrets/AFPA/minilib_db_user
  service_npm_token:
    name: service_npm_token
    file: ${HENDEC_NPM_TOKEN_FILE}

# Outside script for debug
#export HENDEC_APP_ENVIRONMENT=AFPA
#export HENDEC_SECRET=${HOME}/.secrets
#export HENDEC_NPM_REGISTERY_APP_USER=${USER}
#export HENDEC_NPM_TOKEN_FILE=${HENDEC_SECRET}/${HENDEC_APP_ENVIRONMENT}/nmp_users/${HENDEC_NPM_REGISTERY_APP_USER}_npm_token

#export HENDEC_NPM_REGISTERY_HOST=192.168.100.10
#export HENDEC_NPM_REGISTERY_PORT=5000
