version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - service_npm_token
      args:
        HENDEC_NPM_REGISTERY_HOST: ${HENDEC_NPM_REGISTERY_HOST}
        HENDEC_NPM_REGISTERY_PORT: ${HENDEC_NPM_REGISTERY_PORT}

    env_file: .env   # runtime uniquement

    ports:
      - "4000:4000"

secrets:
  service_npm_token:
    file: ./secrets/service_npm_token.txt